import io
from datetime import date


def export_to_word(title: str, content: str) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.2)
        section.right_margin = Inches(1.2)

    # Title block
    title_para = doc.add_heading(title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.runs[0]
    run.font.color.rgb = RGBColor(0x0A, 0x6E, 0xD1)

    sub = doc.add_paragraph(f"Generated by SAP AI Assistant  |  {date.today().strftime('%B %d, %Y')}")
    sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub.runs[0].font.size = Pt(10)
    sub.runs[0].font.color.rgb = RGBColor(0x60, 0x60, 0x60)

    doc.add_paragraph("")

    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped:
            doc.add_paragraph("")
            continue
        if set(stripped) <= set("═─=─-"):
            continue

        # Detect numbered section headings like "1. TITLE" or "1.1 TITLE"
        is_section = False
        if stripped and stripped[0].isdigit():
            parts = stripped.split(".", 1)
            if len(parts) == 2 and parts[0].isdigit():
                doc.add_heading(stripped, level=2)
                is_section = True

        if not is_section:
            if stripped.isupper() and len(stripped) > 4 and len(stripped) < 80:
                doc.add_heading(stripped, level=3)
            elif stripped.startswith("- ") or stripped.startswith("• "):
                p = doc.add_paragraph(stripped[2:], style="List Bullet")
            elif stripped.startswith("| "):
                p = doc.add_paragraph(stripped)
                p.runs[0].font.name = "Courier New"
                p.runs[0].font.size = Pt(8)
            else:
                doc.add_paragraph(stripped)

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


def export_to_pdf(title: str, content: str) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import cm
    from reportlab.lib import colors
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2.5 * cm,
        rightMargin=2.5 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()

    sap_blue = colors.HexColor("#0A6ED1")
    sap_dark = colors.HexColor("#005ABA")

    title_style = ParagraphStyle(
        "SAPTitle",
        parent=styles["Title"],
        fontSize=20,
        textColor=sap_blue,
        spaceAfter=4,
        fontName="Helvetica-Bold",
    )
    sub_style = ParagraphStyle(
        "SAPSub",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.grey,
        spaceAfter=16,
        alignment=1,
    )
    h2_style = ParagraphStyle(
        "SAPH2",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=sap_dark,
        spaceBefore=14,
        spaceAfter=4,
        fontName="Helvetica-Bold",
    )
    h3_style = ParagraphStyle(
        "SAPH3",
        parent=styles["Heading3"],
        fontSize=10,
        textColor=sap_blue,
        spaceBefore=8,
        spaceAfter=2,
        fontName="Helvetica-Bold",
    )
    body_style = ParagraphStyle(
        "SAPBody",
        parent=styles["Normal"],
        fontSize=9,
        leading=14,
        spaceAfter=2,
    )
    mono_style = ParagraphStyle(
        "SAPMono",
        parent=styles["Normal"],
        fontSize=8,
        fontName="Courier",
        leading=12,
        spaceAfter=1,
    )

    story = [
        Paragraph(_safe(title), title_style),
        Paragraph(f"Generated by SAP AI Assistant  |  {date.today().strftime('%B %d, %Y')}", sub_style),
        HRFlowable(width="100%", thickness=1.5, color=sap_blue, spaceAfter=12),
    ]

    for line in content.split("\n"):
        stripped = line.strip()
        if not stripped or set(stripped) <= set("═─=─-"):
            story.append(Spacer(1, 0.15 * cm))
            continue

        is_section = False
        if stripped and stripped[0].isdigit():
            parts = stripped.split(".", 1)
            if len(parts) == 2 and parts[0].isdigit():
                story.append(Paragraph(_safe(stripped), h2_style))
                is_section = True

        if not is_section:
            if stripped.isupper() and 4 < len(stripped) < 80:
                story.append(Paragraph(_safe(stripped), h3_style))
            elif stripped.startswith("| "):
                story.append(Paragraph(_safe(stripped), mono_style))
            else:
                story.append(Paragraph(_safe(stripped), body_style))

    doc.build(story)
    buf.seek(0)
    return buf.read()


def _safe(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
