import io
import zipfile
from datetime import date

_FILE_MARKER_PREFIX = "---FILE:"
_FILE_MARKER_SUFFIX = "---"

_EXT_MAP = {
    "abap": ".abap",
    "ui5": ".js",
    "cap_node": ".js",
    "cap_java": ".java",
}


def package_code_as_zip(
    generated_code: dict,
    functional_spec: str = "",
    technical_spec: str = "",
) -> bytes:
    buf = io.BytesIO()
    manifest_lines = [
        "SAP AI Assistant - Generated Code Package",
        "=" * 42,
        f"Generated : {date.today().strftime('%B %d, %Y')}",
        "",
        "Contents",
        "--------",
    ]

    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        folder_map = {
            "abap": "ABAP/",
            "ui5": "SAPUI5/",
            "cap_node": "CAP_NodeJS/",
            "cap_java": "CAP_Java/",
        }

        for key, data in generated_code.items():
            folder = folder_map.get(key, f"{key}/")
            default_ext = _EXT_MAP.get(key, ".txt")
            _write_parsed_files(zf, data["code"], folder, default_ext)
            manifest_lines.append(f"  {folder}  ({data['type']})")

        if functional_spec:
            zf.writestr("docs/Functional_Specification.txt", functional_spec)
            manifest_lines.append("  docs/Functional_Specification.txt")

        if technical_spec:
            zf.writestr("docs/Technical_Specification.txt", technical_spec)
            manifest_lines.append("  docs/Technical_Specification.txt")

        manifest_lines += [
            "",
            "Deployment Notes",
            "----------------",
            "1. Review all generated code carefully before transport.",
            "2. Validate syntax in your SAP system (SE80 / ADT / BAS).",
            "3. Follow your organisation transport & change management process.",
            "4. Test thoroughly in DEV and QAS before production deployment.",
            "",
            "Generated by SAP AI Assistant",
            "Powered by SAP AI Core / GROQ LLM",
        ]

        zf.writestr("README.txt", "\n".join(manifest_lines))

    buf.seek(0)
    return buf.read()


def _write_parsed_files(
    zf: zipfile.ZipFile, content: str, folder: str, default_ext: str
):
    current_name = None
    current_lines: list[str] = []

    for line in content.split("\n"):
        if line.startswith(_FILE_MARKER_PREFIX) and line.endswith(_FILE_MARKER_SUFFIX):
            if current_name and current_lines:
                zf.writestr(folder + current_name, "\n".join(current_lines))
            current_name = (
                line[len(_FILE_MARKER_PREFIX) : -len(_FILE_MARKER_SUFFIX)].strip()
            )
            current_lines = []
        else:
            current_lines.append(line)

    if current_name and current_lines:
        zf.writestr(folder + current_name, "\n".join(current_lines))
    elif not current_name:
        zf.writestr(folder + "generated_code" + default_ext, content)
